### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Tangjunjun0925** [lehaifeng/DASNet#12]
There are some thing wrong with the BCDD pretrained model.
![image](https://user-images.githubusercontent.com/41275973/82321268-284ffa00-9a07-11ea-8270-ea26342aa686.png)

**Comment by Tangjunjun0925** [comment]
The CDD pretrained model has the same problem.

**Comment by lehaifeng** [comment]
Hi, Tangjunjun0925, would you please descript the problems with more details?

**Comment by lehaifeng** [comment]
HI trangjunjun, It's a missing key error. You may lose something when you use the model.

We have tested it many times without errors.

**Comment by raminrahimi6970** [comment]
I have same problem of pretrained  model because the wights of fc layer dose not exist in uploaded file for CCD and BCCD?
thanks

**Comment by lehaifeng** [comment]
Hi, you can found that in the forward() of Deeplab_V2, "fc" layers are not seem to be used. So "fc" layers have no effect to the result. So if you want to use the pre-training model, you can remove the fc layer from the network structure.

**Comment by Tangjunjun0925** [comment]
I deleted the definition code of the "fc" layers, and the problem was solved. Thank you very much.
