### ISSUE TITLE
使用本项目应用于实际检测

### ISSUE THREAD

**Issue by TingquanGao** [lehaifeng/DASNet#13]
作者你好！
在使用本项目进行实际检测时，是不是需要先对待检测的图像进行配准呢？

**Comment by lehaifeng** [comment]
HI Tingquan,
you didn't need to do this.  :)  A train data set is what you need.

**Comment by TingquanGao** [comment]
> HI Tingquan,
> you didn't need to do this. :) A train data set is what you need.

Thanks for your answer !
