### ISSUE TITLE
关于BCDD数据集

### ISSUE THREAD

**Issue by lsh1994** [lehaifeng/DASNet#17]
你好，BCDD被划分成了多少数据。只知道有个8:1:1，但是总量是多少呢？如果可以，希望作者可以提供训练用的测试、训练、验证数据集或其脚本

**Comment by wangshihuang** [comment]
楼上大哥，能不能提供一下BCDD的下载链接

> 你好，BCDD被划分成了多少数据。只知道有个8:1:1，但是总量是多少呢？如果可以，希望作者可以提供训练用的测试、训练、验证数据集或其脚本

**Comment by lsh1994** [comment]
这个问题看来有点难。

**Comment by Luiweony** [comment]
你好，请问BCDD数据集在哪里可以下载呢？下载的数据集是处理好的还是需要自己处理呢？

**Comment by 1998wq** [comment]
> 你好，请问BCDD数据集在哪里可以下载呢？下载的数据集是处理好的还是需要自己处理呢？

你好，你下载了BCDD数据集没，我也没找见下载链接

**Comment by 1998wq** [comment]
> 你好，请问BCDD数据集在哪里可以下载呢？下载的数据集是处理好的还是需要自己处理呢？

你好，我下载好了数据集，可以添加联系方式谈论一下吗，我的qq:1994462220

**Comment by 1998wq** [comment]
> 你好，BCDD被划分成了多少数据。只知道有个8:1:1，但是总量是多少呢？如果可以，希望作者可以提供训练用的测试、训练、验证数据集或其脚本

你好，我下载好了数据集，可以添加联系方式谈论一下吗，我的qq:1994462220
