### ISSUE TITLE
为什么我的loss负几百，有一样情况的吗，我没有更改代码

### ISSUE THREAD

**Issue by Canoeof** [lehaifeng/DASNet#36]

**Comment by RyougiShiki12** [comment]
我也是训练的有这个问题，请问你解决了没有

**Comment by Canoeof** [comment]
没有，放弃这个了，好像没啥人能复现------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月10日(星期一) 晚上8:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lehaifeng/DASNet] 为什么我的loss负几百，有一样情况的吗，我没有更改代码 (#36)

**Comment by RyougiShiki12** [comment]
尴尬，我也是感觉差别有点大

**Comment by Canoeof** [comment]
issues下面全是质疑的就看出来了……------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月10日(星期一) 晚上8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lehaifeng/DASNet] 为什么我的loss负几百，有一样情况的吗，我没有更改代码 (#36)

**Comment by Luiweony** [comment]
我也是训练有这个问题，而且效果还不怎么好，请问你们解决了吗？是不是那里没有修改正确？

**Comment by RyougiShiki12** [comment]
> 我也是训练有这个问题，而且效果还不怎么好，请问你们解决了吗？是不是那里没有修改正确？

我感觉他代码有问题。。我吧CDD放上去直接RUN的

**Comment by lehaifeng** [comment]
> 我感觉他代码有问题。。我吧CDD放上去直接RUN的

please refer to readme file.
The main reason might be that you did not revise the label from the original label value 0-255 to the network value 0-1.

**Comment by coocooon** [comment]
> > 我感觉他代码有问题。。我吧CDD放上去直接RUN的
> 
> please refer to readme file.
> The main reason might be that you did not revise the label from the original label value 0-255 to the network value 0-1.

Hello, may I ask how to convert the pixel value to 0 to 1. Is it to directly divide the pixel value by 255, or first turn it into a grayscale format, and then divide by 255.Thank you very much and look forward to your reply.

**Comment by lilili-today** [comment]
> > 我感觉他代码有问题。。我吧CDD放上去直接RUN的
> 
> please refer to readme file.
> The main reason might be that you did not revise the label from the original label value 0-255 to the network value 0-1.

你好，请问怎么把原始label的值从0-255转换成0-1，谢谢！

**Comment by dmzlingyin** [comment]
情况就是这么个情况，具体咋改也不知道

Epoch [27/1120] Loss: -752.6592 Mask_Loss_conv5: -251.0686 Mask_Loss_fc: -250.4772 Mask_Loss_embedding: -251.1134
Epoch [27/1140] Loss: -673.4584 Mask_Loss_conv5: -224.4770 Mask_Loss_fc: -224.6068 Mask_Loss_embedding: -224.3746
Epoch [27/1160] Loss: -148.1745 Mask_Loss_conv5: -49.3769 Mask_Loss_fc: -49.4018 Mask_Loss_embedding: -49.3958
Epoch [27/1180] Loss: -71.9143 Mask_Loss_conv5: -23.9587 Mask_Loss_fc: -24.0065 Mask_Loss_embedding: -23.9490
Epoch [27/1200] Loss: -362.3986 Mask_Loss_conv5: -120.7738 Mask_Loss_fc: -120.8340 Mask_Loss_embedding: -120.7908
Epoch [27/1220] Loss: -190.4212 Mask_Loss_conv5: -63.4736 Mask_Loss_fc: -63.4761 Mask_Loss_embedding: -63.4716
Epoch [27/1240] Loss: -55.3082 Mask_Loss_conv5: -18.4365 Mask_Loss_fc: -18.4353 Mask_Loss_embedding: -18.4363
0.058823529411764705
0.0030097260885289996
Epoch [28/0] Loss: -342.8940 Mask_Loss_conv5: -114.2997 Mask_Loss_fc: -114.3042 Mask_Loss_embedding: -114.2901

**Comment by li670** [comment]
> 

兄弟解决了吗

**Comment by stiwfmjX** [comment]
> > 我感觉他代码有问题。。我吧CDD放上去直接RUN的
> 
> please refer to readme file. The main reason might be that you did not revise the label from the original label value 0-255 to the network value 0-1.

你好，原始CDD数据集label的值是在0到255之间的，请问怎么将这个灰度图转换成为二值图，介于0-255之间的数要怎么处理呢？

**Comment by 1998wq** [comment]
> 我也是训练有这个问题,而且效果还不怎么好,请问你们解决了吗？是不是那里没有修改正确？

你好，我想问一下，这数据集的标签不就是二值图像，就是0和1吗，怎么要转换

**Comment by 1998wq** [comment]
> 情况就是这么个情况,具体咋改也不知道
> 
> epoch[27/1120]Loss:-752.6592 Mask _ Loss _ con V5:-251.0686 Mask _ Loss _ fc:-250.4772 Mask _ Loss _ embedding:-251.1134epoch[27/1140]Loss:-673.4584 Mask _ Loss _ con V5:-224.4770 Mask _ Loss _ fc:-224.6068 Mask _ Loss _ embedding:-224.3746epoch[27/1160]Loss:-148.1745 Mask _ Loss _ con V5:-49.3769 Mask _ Loss _ fc:-49.4018 Mask _ Loss _ embedding:-49.3958epoch[27/1180]Loss:-71.9143 Mask _ Loss _ con V5:-23.9587 Mask _ Loss _ fc:-24.0065 Mask _ Loss _ embedding:-23.9490epoch[27/1200]Loss:-362.3986 Mask _ Loss _ con V5:-120.7738 Mask _ Loss _ fc:-120.8340 Mask _ Loss _ embedding:-120.7908epoch[27/1220]Loss:-190.4212 Mask _ Loss _ con V5:-63.4736 Mask _ Loss _ fc:-63.4761 Mask _ Loss _ embedding:-63.4716epoch[27/1240]Loss:-55.3082 Mask _ Loss _ con V5:-18.4365 Mask _ Loss _ fc:-18.4353 Mask _ Loss _ embedding:-18.4363 0.058823529411764705 0.0030097260885289996epoch[28/0]Loss:-342.8940 Mask _ Loss _ con V5:-114.2997 Mask _ Loss _ fc:-114.3042 Mask _ Loss _ embedding:-114.2901

你好，我也出现了这个情况，可以添加你联系方式探讨一下这个问题吗
我qq:1994462220 祝你好运

**Comment by WesternTrail** [comment]
![image](https://user-images.githubusercontent.com/28615285/226666166-62d5b6e1-4e8a-420e-9803-78c606bbc6f4.png)

我是用的BCD跑的，这命令行看的我强迫症都犯了，epoch开始那是什么鬼？还有怎么还有负数的loss???
